"""Re-add stats tables

Revision ID: 2b3e9c920e0c
Revises: c2c2005c187d
Create Date: 2026-01-10 09:20:00.358781

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2b3e9c920e0c"
down_revision: Union[str, Sequence[str], None] = "c2c2005c187d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baseball_team_game_stats",
        sa.Column("team_game_stats_id", sa.Integer(), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=True),
        sa.Column("errors", sa.Integer(), nullable=True),
        sa.Column("home_runs", sa.Integer(), nullable=True),
        sa.Column("walks", sa.Integer(), nullable=True),
        sa.Column("strikeouts", sa.Integer(), nullable=True),
        sa.Column(
            "stats_json", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.ForeignKeyConstraint(["team_game_stats_id"], ["team_game_stats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_game_stats_id"),
    )
    op.create_table(
        "football_team_game_stats",
        sa.Column("team_game_stats_id", sa.Integer(), nullable=False),
        sa.Column("yards_total", sa.Integer(), nullable=True),
        sa.Column("turnovers", sa.Integer(), nullable=True),
        sa.Column(
            "stats_json", sa.JSON().with_variant(postgresql.JSONB(), "postgresql"), nullable=True
        ),
        sa.ForeignKeyConstraint(["team_game_stats_id"], ["team_game_stats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_game_stats_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("football_team_game_stats")
    op.drop_table("baseball_team_game_stats")
    # ### end Alembic commands ###
