"""add books and odds snapshots

Revision ID: 31e801428719
Revises: 9c50cc1a5a7d
Create Date: 2025-12-28 09:45:50.880241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31e801428719'
down_revision: Union[str, Sequence[str], None] = '9c50cc1a5a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_books_is_active', 'books', ['is_active'], unique=False)
    op.create_index('ix_books_key', 'books', ['key'], unique=True)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('market_type', sa.Enum('SPREAD', 'TOTAL', 'MONEYLINE', name='markettypeenum'), nullable=False),
    sa.Column('side_type', sa.Enum('HOME', 'AWAY', 'OVER', 'UNDER', name='sidetypeenum'), nullable=False),
    sa.Column('line', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_closing', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('provider', sa.String(), server_default='odds-api', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_odds_snapshots_book_captured_at', 'odds_snapshots', ['book_id', 'captured_at'], unique=False)
    op.create_index('ix_odds_snapshots_game_captured_at', 'odds_snapshots', ['game_id', 'captured_at'], unique=False)
    op.create_index('ix_odds_snapshots_lookup', 'odds_snapshots', ['game_id', 'book_id', 'market_type', 'side_type', 'captured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_odds_snapshots_lookup', table_name='odds_snapshots')
    op.drop_index('ix_odds_snapshots_game_captured_at', table_name='odds_snapshots')
    op.drop_index('ix_odds_snapshots_book_captured_at', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index('ix_books_key', table_name='books')
    op.drop_index('ix_books_is_active', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
