"""Add null constraint to game.seasonid

Revision ID: 402788dd9949
Revises: 17e93190076f
Create Date: 2026-01-03 13:33:31.686476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "402788dd9949"
down_revision: Union[str, Sequence[str], None] = "17e93190076f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("games", "season_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint(op.f("games_season_id_fkey"), "games", type_="foreignkey")
    op.create_foreign_key(None, "games", "seasons", ["season_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "games", type_="foreignkey")
    op.create_foreign_key(
        op.f("games_season_id_fkey"), "games", "seasons", ["season_id"], ["id"], ondelete="SET NULL"
    )
    op.alter_column("games", "season_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
