"""add indexes for odds snapshots

Revision ID: 5451a068834a
Revises: cab44564d739
Create Date: 2025-12-31 14:56:09.318272

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5451a068834a"
down_revision: Union[str, Sequence[str], None] = "cab44564d739"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_odds_snapshots_closing_by_game_market_side",
        "odds_snapshots",
        ["game_id", "market_type", "side_type"],
        unique=False,
        postgresql_where=sa.text("is_closing = true"),
    )
    op.create_index(
        "ix_odds_snapshots_game_market_side_captured_at",
        "odds_snapshots",
        ["game_id", "market_type", "side_type", "captured_at"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_odds_snapshots_identity",
        "odds_snapshots",
        ["game_id", "book_id", "market_type", "side_type", "captured_at"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_odds_snapshots_identity", "odds_snapshots", type_="unique")
    op.drop_index("ix_odds_snapshots_game_market_side_captured_at", table_name="odds_snapshots")
    op.drop_index(
        "ix_odds_snapshots_closing_by_game_market_side",
        table_name="odds_snapshots",
        postgresql_where=sa.text("is_closing = true"),
    )
    # ### end Alembic commands ###
