"""Abstract sport-specific game stats

Revision ID: 6b82c3bea123
Revises: f91355058ef0
Create Date: 2026-01-07 08:40:18.013212

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6b82c3bea123"
down_revision: Union[str, Sequence[str], None] = "f91355058ef0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baseball_team_game_stats",
        sa.Column("team_game_stats_id", sa.Integer(), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=True),
        sa.Column("errors", sa.Integer(), nullable=True),
        sa.Column("home_runs", sa.Integer(), nullable=True),
        sa.Column("walks", sa.Integer(), nullable=True),
        sa.Column("strikeouts", sa.Integer(), nullable=True),
        sa.Column("stats_json", postgresql.JSONB(), nullable=True),
        sa.ForeignKeyConstraint(["team_game_stats_id"], ["team_game_stats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_game_stats_id"),
    )
    op.create_table(
        "football_team_game_stats",
        sa.Column("team_game_stats_id", sa.Integer(), nullable=False),
        sa.Column("yards_total", sa.Integer(), nullable=True),
        sa.Column("turnovers", sa.Integer(), nullable=True),
        sa.Column("stats_json", postgresql.JSONB(), nullable=True),
        sa.ForeignKeyConstraint(["team_game_stats_id"], ["team_game_stats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("team_game_stats_id"),
    )
    op.drop_constraint(op.f("games_provider_game_id_key"), "games", type_="unique")
    op.drop_index(op.f("ix_games_season_week"), table_name="games")
    op.create_index(
        "ix_games_season_start_time", "games", ["season_id", "start_time"], unique=False
    )
    op.create_unique_constraint(
        "uq_games_league_provider_game_id", "games", ["league_id", "provider_game_id"]
    )
    op.add_column("team_game_stats", sa.Column("score", sa.Integer(), nullable=True))
    op.drop_index(op.f("ix_team_game_stats_team_game"), table_name="team_game_stats")
    op.create_index("ix_tgs_game_id", "team_game_stats", ["game_id"], unique=False)
    op.create_index("ix_tgs_team_id", "team_game_stats", ["team_id"], unique=False)
    op.drop_column("team_game_stats", "points")
    op.drop_column("team_game_stats", "turnovers")
    op.drop_column("team_game_stats", "yards_total")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team_game_stats",
        sa.Column("yards_total", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "team_game_stats", sa.Column("turnovers", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "team_game_stats", sa.Column("points", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_index("ix_tgs_team_id", table_name="team_game_stats")
    op.drop_index("ix_tgs_game_id", table_name="team_game_stats")
    op.create_index(
        op.f("ix_team_game_stats_team_game"),
        "team_game_stats",
        ["team_id", "game_id"],
        unique=False,
    )
    op.drop_column("team_game_stats", "score")
    op.drop_constraint("uq_games_league_provider_game_id", "games", type_="unique")
    op.drop_index("ix_games_season_start_time", table_name="games")
    op.create_index(op.f("ix_games_season_week"), "games", ["season_id", "week"], unique=False)
    op.create_unique_constraint(
        op.f("games_provider_game_id_key"),
        "games",
        ["provider_game_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_table("football_team_game_stats")
    op.drop_table("baseball_team_game_stats")
    # ### end Alembic commands ###
