"""Add yards and turnovers

Revision ID: b1b58e877b9c
Revises: ddec2ac75b1b
Create Date: 2026-01-09 18:13:47.298629

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b1b58e877b9c"
down_revision: Union[str, Sequence[str], None] = "ddec2ac75b1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("baseball_team_game_stats")
    op.drop_table("football_team_game_stats")
    op.add_column("team_game_state", sa.Column("off_yards_l3", sa.Float(), nullable=False))
    op.add_column("team_game_state", sa.Column("off_yards_l5", sa.Float(), nullable=False))
    op.add_column("team_game_state", sa.Column("off_yards_season", sa.Float(), nullable=False))
    op.add_column("team_game_state", sa.Column("off_turnovers_l3", sa.Float(), nullable=False))
    op.add_column("team_game_state", sa.Column("off_turnovers_l5", sa.Float(), nullable=False))
    op.add_column("team_game_state", sa.Column("off_turnovers_season", sa.Float(), nullable=False))
    op.add_column("team_game_state", sa.Column("def_yards_allowed_l3", sa.Float(), nullable=False))
    op.add_column("team_game_state", sa.Column("def_yards_allowed_l5", sa.Float(), nullable=False))
    op.add_column(
        "team_game_state", sa.Column("def_yards_allowed_season", sa.Float(), nullable=False)
    )
    op.add_column("team_game_state", sa.Column("def_takeaways_l3", sa.Float(), nullable=False))
    op.add_column("team_game_state", sa.Column("def_takeaways_l5", sa.Float(), nullable=False))
    op.add_column("team_game_state", sa.Column("def_takeaways_season", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_game_state", "def_takeaways_season")
    op.drop_column("team_game_state", "def_takeaways_l5")
    op.drop_column("team_game_state", "def_takeaways_l3")
    op.drop_column("team_game_state", "def_yards_allowed_season")
    op.drop_column("team_game_state", "def_yards_allowed_l5")
    op.drop_column("team_game_state", "def_yards_allowed_l3")
    op.drop_column("team_game_state", "off_turnovers_season")
    op.drop_column("team_game_state", "off_turnovers_l5")
    op.drop_column("team_game_state", "off_turnovers_l3")
    op.drop_column("team_game_state", "off_yards_season")
    op.drop_column("team_game_state", "off_yards_l5")
    op.drop_column("team_game_state", "off_yards_l3")
    op.create_table(
        "football_team_game_stats",
        sa.Column("team_game_stats_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("yards_total", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("turnovers", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stats_json", postgresql.JSONB(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["team_game_stats_id"],
            ["team_game_stats.id"],
            name=op.f("football_team_game_stats_team_game_stats_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("team_game_stats_id", name=op.f("football_team_game_stats_pkey")),
    )
    op.create_table(
        "baseball_team_game_stats",
        sa.Column("team_game_stats_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("hits", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("errors", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("home_runs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("walks", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("strikeouts", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stats_json", postgresql.JSONB(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["team_game_stats_id"],
            ["team_game_stats.id"],
            name=op.f("baseball_team_game_stats_team_game_stats_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("team_game_stats_id", name=op.f("baseball_team_game_stats_pkey")),
    )
    # ### end Alembic commands ###
