"""remove superfluous fields

Revision ID: cab44564d739
Revises: 31e801428719
Create Date: 2025-12-31 10:42:16.278282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cab44564d739"
down_revision: Union[str, Sequence[str], None] = "31e801428719"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "stage")
    op.drop_column("games", "game_number")
    op.drop_column("games", "week_source")
    op.drop_column("games", "week_label")
    op.drop_constraint(op.f("uq_seasons_league_year_type"), "seasons", type_="unique")
    op.create_unique_constraint("uq_seasons_league_year", "seasons", ["league_id", "year"])
    op.drop_column("seasons", "season_type")
    op.add_column("teams", sa.Column("market", sa.String(), nullable=True))
    op.drop_column("teams", "city")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("teams", "market")
    op.add_column(
        "seasons",
        sa.Column(
            "season_type",
            postgresql.ENUM("PRE", "REG", "POST", "OTHER", name="seasontypeenum"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint("uq_seasons_league_year", "seasons", type_="unique")
    op.create_unique_constraint(
        op.f("uq_seasons_league_year_type"),
        "seasons",
        ["league_id", "year", "season_type"],
        postgresql_nulls_not_distinct=False,
    )
    op.add_column(
        "games", sa.Column("week_label", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "games", sa.Column("week_source", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "games", sa.Column("game_number", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column("games", sa.Column("stage", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
