"""Add team_game_state

Revision ID: d108ed7d52ed
Revises: 5451a068834a
Create Date: 2026-01-01 09:34:47.810802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d108ed7d52ed"
down_revision: Union[str, Sequence[str], None] = "5451a068834a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_game_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("games_played", sa.Integer(), nullable=False),
        sa.Column("avg_points_for", sa.Float(), nullable=True),
        sa.Column("avg_points_against", sa.Float(), nullable=True),
        sa.Column("avg_point_diff", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "game_id", name="uq_team_game_state_team_game"),
    )
    op.create_index("ix_team_game_state_game", "team_game_state", ["game_id"], unique=False)
    op.create_index(
        "ix_team_game_state_season_week", "team_game_state", ["season_id", "week"], unique=False
    )
    op.create_index(
        "ix_team_game_state_team_start_time",
        "team_game_state",
        ["team_id", "start_time"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_team_game_state_team_start_time", table_name="team_game_state")
    op.drop_index("ix_team_game_state_season_week", table_name="team_game_state")
    op.drop_index("ix_team_game_state_game", table_name="team_game_state")
    op.drop_table("team_game_state")
    # ### end Alembic commands ###
