"""add off/def windows to team_game_state

Revision ID: d858976b5142
Revises: 9955d64fa0fb
Create Date: 2026-01-03 08:11:11.043191

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d858976b5142"
down_revision: Union[str, Sequence[str], None] = "9955d64fa0fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team_game_state", sa.Column("off_pts_l3", sa.Float(), nullable=True))
    op.add_column("team_game_state", sa.Column("off_pts_l5", sa.Float(), nullable=True))
    op.add_column("team_game_state", sa.Column("off_pts_season", sa.Float(), nullable=True))
    op.add_column("team_game_state", sa.Column("off_diff_l3", sa.Float(), nullable=True))
    op.add_column("team_game_state", sa.Column("off_diff_l5", sa.Float(), nullable=True))
    op.add_column("team_game_state", sa.Column("off_diff_season", sa.Float(), nullable=True))
    op.add_column("team_game_state", sa.Column("def_pa_l3", sa.Float(), nullable=True))
    op.add_column("team_game_state", sa.Column("def_pa_l5", sa.Float(), nullable=True))
    op.add_column("team_game_state", sa.Column("def_pa_season", sa.Float(), nullable=True))
    op.add_column("team_game_state", sa.Column("def_diff_l3", sa.Float(), nullable=True))
    op.add_column("team_game_state", sa.Column("def_diff_l5", sa.Float(), nullable=True))
    op.add_column("team_game_state", sa.Column("def_diff_season", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_game_state", "def_diff_season")
    op.drop_column("team_game_state", "def_diff_l5")
    op.drop_column("team_game_state", "def_diff_l3")
    op.drop_column("team_game_state", "def_pa_season")
    op.drop_column("team_game_state", "def_pa_l5")
    op.drop_column("team_game_state", "def_pa_l3")
    op.drop_column("team_game_state", "off_diff_season")
    op.drop_column("team_game_state", "off_diff_l5")
    op.drop_column("team_game_state", "off_diff_l3")
    op.drop_column("team_game_state", "off_pts_season")
    op.drop_column("team_game_state", "off_pts_l5")
    op.drop_column("team_game_state", "off_pts_l3")
    # ### end Alembic commands ###
