"""Remove stas_json from base stats model

Revision ID: ddec2ac75b1b
Revises: 6b82c3bea123
Create Date: 2026-01-07 09:33:59.457734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ddec2ac75b1b"
down_revision: Union[str, Sequence[str], None] = "6b82c3bea123"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_game_stats", "stats_json")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team_game_stats",
        sa.Column("stats_json", postgresql.JSONB(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
