"""Add window_size to team_game_state

Revision ID: e767c858f106
Revises: d108ed7d52ed
Create Date: 2026-01-01 09:51:18.493117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e767c858f106"
down_revision: Union[str, Sequence[str], None] = "d108ed7d52ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team_game_state", sa.Column("window_size", sa.Integer(), nullable=False))
    op.create_index(
        "ix_team_game_state_team_window",
        "team_game_state",
        ["team_id", "window_size", "start_time"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_team_game_state_team_game_window",
        "team_game_state",
        ["team_id", "game_id", "window_size"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_team_game_state_team_game_window", "team_game_state", type_="unique")
    op.drop_index("ix_team_game_state_team_window", table_name="team_game_state")
    op.drop_column("team_game_state", "window_size")
    # ### end Alembic commands ###
