"""Remove window_size

Revision ID: f91355058ef0
Revises: 402788dd9949
Create Date: 2026-01-03 15:27:49.048827

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f91355058ef0"
down_revision: Union[str, Sequence[str], None] = "402788dd9949"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_team_game_state_team_window"), table_name="team_game_state")
    op.drop_column("team_game_state", "window_size")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "team_game_state",
        sa.Column("window_size", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f("ix_team_game_state_team_window"),
        "team_game_state",
        ["team_id", "window_size", "start_time"],
        unique=False,
    )
    # ### end Alembic commands ###
